### ISSUE TITLE
Problem during parsing

### ISSUE THREAD

**Issue by rkaldung** [reneeb/OPM-Maker#7]
I have a huge opm (ITSM bundle) to index and the execution failed with this error message:

```
usr/local/bin/opmbuild index "$PATH" > "${PATH}/otrs.xml"
$PATH/ITSM-6.0.31.opm:22: parser error : xmlSAX2Characters: huge text node
```

Any ideas?

**Comment by reneeb** [comment]
Fixed with commit 1dde70f30eafacb82e5cb09baa665d66e0f53c9e. See https://github.com/reneeb/OPM-Maker#parsing-huge-files 

The release is on its way to CPAN...
